---
title: "&nbsp;"
output:
  distill::distill_article:
    toc: false
    toc_depth: 3

---

```{r setup, include=FALSE}

library(janitor)
library(gsheet)
library(tidyverse)
library(crosstalk)
library(DT)
library(ggthemes)
library(plotly)
library(cowplot)
Sys.setlocale("LC_ALL", "pt_BR.UTF-8")


dat0 <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1YfZlPXn9jwRfneV4j5lmNpRQcQh0LWc8/edit?gid=2097200067#gid=2097200067")

dat1 <- dat0 %>% 
  select(`Nome do egresso`, Nível, `Gênero`, Orientador, Defesa, Nacionalidade, `Tipo de vínculo`) 

```


### Total estrangeiro/país de origem
```{r echo=FALSE}

estrangeiro <- dat1 %>% 
  filter(Nacionalidade != "Brasil") %>% 
     tabyl(Nacionalidade,  Nível) %>% 
  pivot_longer(2:3, names_to = "nivel" , values_to = "n") %>% 
  ggplot(aes(x = reorder(Nacionalidade, n), y = n, fill = nivel))+
  geom_col()+
scale_y_continuous(breaks = seq(0, 16, by = 2), limits = c(0, 14))+
  coord_flip()+
    scale_fill_pander()+
  theme_minimal_vgrid(font_size = 10)+
  labs(x = "", y = "Número de egressos", fill = "Nível")
    
ggplotly(estrangeiro)
```


