---
title: "Egressos Fitopatologia UFV"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(flexdashboard)
library(tidyverse)
library(crosstalk)
library(plotly)
library(viridis)
library(gsheet)

library(DT)
library(janitor)
library(cowplot)
theme_set(theme_minimal_hgrid())
library(ggthemes)
```



```{r load data, message=FALSE, warning=FALSE, include=FALSE}
Sys.setlocale("LC_ALL", "pt_BR.UTF-8")


dat0 <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1l_p2gx1kGjMypej5dKscw2wzugaRNUkuzFEc38qfk8E/edit?usp=sharing")


dat1 <- dat0 %>% 
  select(nome, nivel, defesa, orientador, vinculo)


dat2 <- dat0 %>% 
  select(nome, nivel, defesa, sexo, orientador, vinculo, nacionalidade)

```



```{r all table, echo=FALSE}
sd <- SharedData$new(dat1)

```


Dashboard 
============


Column {.sidebar}
-------------------------------------



### Quick filter


```{r}
filter_slider("Ano de defesa", "Restringe aos anos", sd, ~defesa,
              round = TRUE)

filter_select("orientador", "Orientador", sd, ~orientador,
              multiple = FALSE)
filter_checkbox("Nível", "Nível", sd, ~ nivel, 
                inline = TRUE)

```


Column {data-width=700 .tabset}
-------------------------------------


### <i class="fa fa-table" aria-hidden="true"></i> Planilha


```{r}
datatable(sd, 
           options = list(
    pageLength= 15,
    scroller = TRUE
  )
)

```

### Total defesas/nível

```{r}
library(cowplot)
theme_set(theme_minimal_hgrid())
dat1 %>% 
  ggplot(aes(x = nivel, fill = nivel))+
  geom_bar()+
  theme_minimal_hgrid(font_size = 9)+
  
  scale_fill_pander()+
  labs(x = "Nível", y = "Número de egressos")
```


### Total defesas/ano

```{r}
dat1 %>% 
  tabyl(defesa, nivel) %>% 
  pivot_longer(2:3, names_to = "nivel", values_to = "n") %>% 
  ggplot(aes(defesa, n, fill = nivel))+
  geom_col()+
    theme_minimal_hgrid(font_size = 9)+
  scale_fill_pander() +
  labs(x = "Ano de defesa", y = "Número de egressos")
```


### Total defesas/orientador

```{r}

dat1 %>% 
  tabyl(orientador, nivel) %>% 
  pivot_longer(2:3, names_to = "nivel", values_to = "n") %>% 
  ggplot(aes(x = reorder(orientador, n),y=  n, fill = nivel))+
  geom_col()+
  coord_flip()+
  scale_fill_pander()+
    theme_minimal_vgrid(font_size = 9)+
  labs(x = "", y = "Número de egressos")
```


### Egressos por sexo
```{r}

dat2 %>% 
  tabyl(sexo,  nivel) %>% 
  pivot_longer(2:3, names_to = "nivel", values_to = "n") %>% 
  ggplot(aes(x = reorder(sexo, n),y=  n, fill = nivel))+
  geom_col()+
  scale_fill_pander()+
    theme_minimal_vgrid(font_size = 9)+
  labs(x = "Sexo", y = "Número de egressos")
```


### Total estrangeiro/país de origem
```{r}

dat2 %>% 
  filter(nacionalidade != "Brasil") %>% 
     tabyl(nacionalidade,  nivel) %>% 
  pivot_longer(2:3, names_to = "nivel" , values_to = "n") %>% 
  ggplot(aes(x = reorder(nacionalidade, n), y = n, fill = nivel))+
  geom_col()+
  coord_flip()+
    scale_fill_pander()+
  theme_minimal_vgrid(font_size = 10)+
  labs(x = "", y = "Número de egressos")
```


### Vinculo atual

```{r}
dat1 %>% 
   tabyl(vinculo,  nivel) %>% 
  pivot_longer(2:3, names_to = "nivel", values_to = "n") %>% 
  ggplot(aes(x = reorder(vinculo, n), y= n,  fill = nivel))+
  geom_col()+
  coord_flip()+
  theme_minimal_vgrid(font_size = 9)+
    scale_fill_pander()
```


Column {data-width=300}
-------------------------------------


### Defesas por nível

```{r}

dat1 %>% 
  ggplot(aes(x = nivel, fill = nivel))+
  geom_bar()+
    scale_fill_pander()+
  labs(x = "Nível", y = "Número de egressos")
```


### Estrangeiros

```{r}

dat2 %>% 
  filter(nacionalidade != "Brasil") %>% 
     tabyl(nacionalidade,  nivel) %>% 
  pivot_longer(2:3, names_to = "nivel" , values_to = "n") %>% 
  ggplot(aes(x = reorder(nacionalidade, n), y = n, fill = nivel))+
  geom_col()+
  coord_flip()+
    scale_fill_pander()+
  theme_minimal_vgrid()+
  labs(x = "", y = "Número de egressos")
```

Atualize seus dados
============


Column {.tabset}
-------------------------------------
